/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as shipSol from "./Ship.sol";
export type { shipSol };
export type { Main } from "./Main";
export * as factories from "./factories";
export { Main__factory } from "./factories/Main__factory";
export type { MyShip } from "./Ship.sol/MyShip";
export { MyShip__factory } from "./factories/Ship.sol/MyShip__factory";
export type { Ship } from "./Ship.sol/Ship";
export { Ship__factory } from "./factories/Ship.sol/Ship__factory";
